doctor/urls.py
from django.urls import path
from . import views
app_name='doctor'
urlpatterns = [      
    path('login', views.loginfun, name='log_in')
]

new_hospital/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctor/',include('doctor.urls')),
    path('patient/',include('patient.urls'))
]

patient/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('booking',views.slotefun),
    
]

doctor/models.py
from django.db import models

# Create your models here.

patient/models.py
from django.db import models

# Create your models here.

doctor/views.py
from django.shortcuts import render

# Create your views here.
def loginfun(request):
    return render(request,'doctor/login.html')

patient/views.py
from django.shortcuts import render

# Create your views here.

def slotefun(request):
    return render(request,'patient/booking.html')
    

doctor/templates/doctor/attendence.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>attendence</h1>
    <img src="{% static %}" alt="">
</body>
</html>

doctor/templates/doctor/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 align="center">Welcome</h1>
    <form action="get">
        <label for="">user id</label>
        <input type="text" placeholder="user id">
        <label for="">password</label>
        <input type="password"> 
        <br>
        <a href="">forgot password</a>
        <img src="{% static 'images/05.jpg'%}" alt="">

        <a href="{% url 'doctor:log_in'%}">connect</a>

    </form>
</body>
</html>

patient/templates/patient/booking.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1 align="center">Welcome</h1>
    <form action="get">
        <label for="">user id</label>
        <input type="text" placeholder="user id">
        <label for="">password</label>
        <input type="password"> 
        <br>
        <img src="{% static 'image/01.jpg'%}" alt="">
</body>
</html>